name: Build oci-ping image

on:
  push:
    paths: ['oci-ping/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to OCIR
        env:
          OCIR_TOKEN: ${{ secrets.OCI_OCIR_AUTH_TOKEN }}
        run: |
          printf '%s' "$OCIR_TOKEN" | docker login xsp.ocir.io \
            --username axfazd56plva/wangsenhu@gmail.com \
            --password-stdin

      - name: Build and Push (AMD64)
        run: |
          docker build --platform linux/amd64 \
            -t xsp.ocir.io/axfazd56plva/gsd-scripts/oci-ping:latest \
            oci-ping/
          docker push xsp.ocir.io/axfazd56plva/gsd-scripts/oci-ping:latest
